version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: rf-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=adminpassword
      - DOCKER_INFLUXDB_INIT_ORG=rf-org
      - DOCKER_INFLUXDB_INIT_BUCKET=rf-spectrum-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=rf-spectrum-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    networks:
      - rf-network

  rf-analyzer:
    build: .
    container_name: rf-spectrum-analyzer
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=rf-spectrum-token
      - INFLUXDB_ORG=rf-org
      - INFLUXDB_BUCKET=rf-spectrum-data
    depends_on:
      - influxdb
    networks:
      - rf-network
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates

volumes:
  influxdb_data:
  influxdb_config:

networks:
  rf-network:
    driver: bridge