version: '3.8'

services:
  influxdb:
    image: influxdb:2.7
    container_name: rf-influxdb
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=rf-password-123
      - DOCKER_INFLUXDB_INIT_ORG=rf-org
      - DOCKER_INFLUXDB_INIT_BUCKET=rf-amplitude-data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=rf-amplitude-token
    volumes:
      - influxdb_data:/var/lib/influxdb2
      - influxdb_config:/etc/influxdb2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  grafana:
    image: grafana/grafana:latest
    container_name: rf-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=rf-grafana-123
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  influxdb_data:
  influxdb_config:
  grafana_data: